print("operation")
a=("Bricks","Gravels","Sand","Cement")
print("Creating a tuple:",a)
print("Indexing:",a[0])
print("Slicing:",a[0:3])
b=("Steelbar","Lubricants")
print("Repitition:",a*2)
print("Membership:","Bricks" in a)
print("Membership:","Bricks" in b)
print("Membership:","Cement" in a)
print("Membership:","Gravels" in a)
print("Comparison:",a==b)